import type { Metadata } from "next";
import { Inter, Stalinist_One } from "next/font/google";
import "./globals.css";
import {
  DynamicContextProvider,
  EthereumWalletConnectors,
} from "@/lib/dynamic";
import { Providers } from "@/lib/providers";
import { DynamicWagmiConnector } from "@dynamic-labs/wagmi-connector";
import { DynamicProvider } from "@/lib/DynamicProvider";

const inter = Inter({ subsets: ["latin"] });
const stalinist = Stalinist_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-stalinist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${(inter.className, stalinist.variable)} `}>
        {children}
      </body>
    </html>
  );
}
